#!/usr/bin/python
# -*- coding: utf-8 -*-


import requests
import bs4


yearinput = raw_input("Year: ")
mdfeeCdinput = raw_input("Code: ").upper()


endpoint = "http://apis.data.go.kr/B551182/mdlrtActionInfoService/getMdlrtActionByClassesStats?"
servicekey = "MSHdqGm%2BtYTAvwvKn%2BkajdvrMSOxJt840YrxsEGGfCHzkClo0BQjI33e%2B5QACU%2FrLNFuf60USAJPlHWA8GgZIg%3D%3D"
mdfeeCd = mdfeeCdinput
medTp = "2"
year = yearinput

paramset = "servicekey=" + servicekey + "&" + "mdfeeCd=" + mdfeeCd + "&" + "medTp=" + medTp + "&" + "year=" + year

url = endpoint + paramset
print("url : " + url)

result = requests.get(url)
bs_obj = bs4.BeautifulSoup(result.content,"html.parser")
items = bs_obj.findAll("execfq01")

data = []
for item in items:
    item = item.text
    tag = item[0:len(item)-6].strip().replace(",","")
    tag = int(tag)
    data.append(tag)

print(data)

grade = bs_obj.findAll("execfq01")
grade